[2025-03-23T17:21:18.875+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T17:21:18.919+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-23T17:18:05.200372+00:00 [queued]>
[2025-03-23T17:21:18.937+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-23T17:18:05.200372+00:00 [queued]>
[2025-03-23T17:21:18.938+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-23T17:21:18.963+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-03-23 17:18:05.200372+00:00
[2025-03-23T17:21:18.976+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-23T17:21:18.980+0000] {standard_task_runner.py:72} INFO - Started process 151 to run task
[2025-03-23T17:21:18.980+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'submit_spark_job', 'manual__2025-03-23T17:18:05.200372+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmpxfuwp7z9']
[2025-03-23T17:21:18.982+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask submit_spark_job
[2025-03-23T17:21:19.092+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-23T17:18:05.200372+00:00 [running]> on host c5bae578e6c2
[2025-03-23T17:21:19.256+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T17:18:05.200372+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T17:18:05.200372+00:00'
[2025-03-23T17:21:19.260+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T17:21:19.305+0000] {base.py:84} INFO - Retrieving connection 'spark_mm'
[2025-03-23T17:21:19.313+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py
[2025-03-23T17:21:23.349+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-23T17:21:25.705+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SparkContext: Running Spark version 3.5.5
[2025-03-23T17:21:25.706+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SparkContext: OS info Linux, 5.15.0-1078-gcp, amd64
[2025-03-23T17:21:25.707+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SparkContext: Java version 17.0.14
[2025-03-23T17:21:25.756+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO ResourceUtils: ==============================================================
[2025-03-23T17:21:25.758+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-23T17:21:25.759+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO ResourceUtils: ==============================================================
[2025-03-23T17:21:25.760+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SparkContext: Submitted application: WeatherDataTransformation
[2025-03-23T17:21:25.802+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-23T17:21:25.816+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO ResourceProfile: Limiting resource is cpu
[2025-03-23T17:21:25.817+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-23T17:21:25.951+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SecurityManager: Changing view acls to: default
[2025-03-23T17:21:25.953+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SecurityManager: Changing modify acls to: default
[2025-03-23T17:21:25.954+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SecurityManager: Changing view acls groups to:
[2025-03-23T17:21:25.955+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SecurityManager: Changing modify acls groups to:
[2025-03-23T17:21:25.956+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:25 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-23T17:21:26.423+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO Utils: Successfully started service 'sparkDriver' on port 41267.
[2025-03-23T17:21:26.536+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO SparkEnv: Registering MapOutputTracker
[2025-03-23T17:21:26.639+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-23T17:21:26.703+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-23T17:21:26.706+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-23T17:21:26.717+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-23T17:21:26.777+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-d03e56f7-4673-441d-bf3b-4b9a5d0aa22c
[2025-03-23T17:21:26.862+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-23T17:21:26.891+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:26 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-23T17:21:27.223+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:27 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-23T17:21:27.386+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:27 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-23T17:21:27.484+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:27 INFO SparkContext: Added JAR /opt/bitnami/spark/jars/postgresql-42.2.23.jar at spark://c5bae578e6c2:41267/jars/postgresql-42.2.23.jar with timestamp 1742750485689
[2025-03-23T17:21:27.486+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:27 INFO SparkContext: Added JAR /opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar at spark://c5bae578e6c2:41267/jars/spark-3.5-bigquery-0.36.5.jar with timestamp 1742750485689
[2025-03-23T17:21:27.487+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:27 INFO SparkContext: Added JAR /opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar at spark://c5bae578e6c2:41267/jars/gcs-connector-hadoop3-latest.jar with timestamp 1742750485689
[2025-03-23T17:21:27.659+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:27 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-03-23T17:21:27.774+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:27 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.5:7077 after 56 ms (0 ms spent in bootstraps)
[2025-03-23T17:21:28.354+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250323172128-0000
[2025-03-23T17:21:28.372+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33587.
[2025-03-23T17:21:28.373+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO NettyBlockTransferService: Server created on c5bae578e6c2:33587
[2025-03-23T17:21:28.387+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-23T17:21:28.405+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, c5bae578e6c2, 33587, None)
[2025-03-23T17:21:28.419+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO BlockManagerMasterEndpoint: Registering block manager c5bae578e6c2:33587 with 434.4 MiB RAM, BlockManagerId(driver, c5bae578e6c2, 33587, None)
[2025-03-23T17:21:28.421+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, c5bae578e6c2, 33587, None)
[2025-03-23T17:21:28.427+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, c5bae578e6c2, 33587, None)
[2025-03-23T17:21:28.440+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250323172128-0000/0 on worker-20250323045618-172.18.0.6-39639 (172.18.0.6:39639) with 2 core(s)
[2025-03-23T17:21:28.444+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:28 INFO StandaloneSchedulerBackend: Granted executor ID app-20250323172128-0000/0 on hostPort 172.18.0.6:39639 with 2 core(s), 1024.0 MiB RAM
[2025-03-23T17:21:29.034+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:29 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-23T17:21:29.313+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:29 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250323172128-0000/0 is now RUNNING
[2025-03-23T17:21:29.619+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:29 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-23T17:21:29.625+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:29 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-23T17:21:32.705+0000] {spark_submit.py:488} INFO - ERROR:root:Error loading data from PostgreSQL: An error occurred while calling o34.jdbc.
[2025-03-23T17:21:32.707+0000] {spark_submit.py:488} INFO - : org.postgresql.util.PSQLException: ERROR: relation "hourly_data" does not exist
[2025-03-23T17:21:32.708+0000] {spark_submit.py:488} INFO - Position: 15
[2025-03-23T17:21:32.709+0000] {spark_submit.py:488} INFO - at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
[2025-03-23T17:21:32.710+0000] {spark_submit.py:488} INFO - at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
[2025-03-23T17:21:32.711+0000] {spark_submit.py:488} INFO - at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
[2025-03-23T17:21:32.713+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
[2025-03-23T17:21:32.714+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
[2025-03-23T17:21:32.715+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
[2025-03-23T17:21:32.716+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
[2025-03-23T17:21:32.717+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.getQueryOutputSchema(JDBCRDD.scala:68)
[2025-03-23T17:21:32.718+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:58)
[2025-03-23T17:21:32.719+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:241)
[2025-03-23T17:21:32.720+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:37)
[2025-03-23T17:21:32.721+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
[2025-03-23T17:21:32.723+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-23T17:21:32.724+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-23T17:21:32.727+0000] {spark_submit.py:488} INFO - at scala.Option.getOrElse(Option.scala:189)
[2025-03-23T17:21:32.730+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-23T17:21:32.732+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2025-03-23T17:21:32.733+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:249)
[2025-03-23T17:21:32.735+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-23T17:21:32.736+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-23T17:21:32.737+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-23T17:21:32.738+0000] {spark_submit.py:488} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-23T17:21:32.743+0000] {spark_submit.py:488} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-23T17:21:32.744+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-23T17:21:32.745+0000] {spark_submit.py:488} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-23T17:21:32.746+0000] {spark_submit.py:488} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-23T17:21:32.747+0000] {spark_submit.py:488} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-23T17:21:32.748+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-23T17:21:32.748+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-23T17:21:32.749+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-23T17:21:32.750+0000] {spark_submit.py:488} INFO - 
[2025-03-23T17:21:32.751+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-23T17:21:32.754+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO SparkUI: Stopped Spark web UI at http://c5bae578e6c2:4040
[2025-03-23T17:21:32.760+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-23T17:21:32.769+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-23T17:21:32.847+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-23T17:21:32.914+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO MemoryStore: MemoryStore cleared
[2025-03-23T17:21:32.915+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO BlockManager: BlockManager stopped
[2025-03-23T17:21:32.932+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-23T17:21:32.933+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-23T17:21:32.989+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:32 INFO SparkContext: Successfully stopped SparkContext
[2025-03-23T17:21:33.304+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:33 INFO ShutdownHookManager: Shutdown hook called
[2025-03-23T17:21:33.305+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-8ac4a470-3664-49e4-8dbf-8032172efced
[2025-03-23T17:21:33.314+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-8ac4a470-3664-49e4-8dbf-8032172efced/pyspark-c2c8f440-8fd6-4278-a043-50b2c761efd3
[2025-03-23T17:21:33.321+0000] {spark_submit.py:488} INFO - 25/03/23 17:21:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-66091f0b-1900-4aeb-b595-b0cf1c2b1d46
[2025-03-23T17:21:33.398+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py. Error code is: 1.
[2025-03-23T17:21:33.415+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_energy_crops_pipeline, task_id=submit_spark_job, run_id=manual__2025-03-23T17:18:05.200372+00:00, execution_date=20250323T171805, start_date=20250323T172118, end_date=20250323T172133
[2025-03-23T17:21:33.481+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T17:21:33.482+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task submit_spark_job (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py. Error code is: 1.; 151)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py. Error code is: 1.
[2025-03-23T17:21:33.517+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-23T17:21:33.576+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T17:21:33.578+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
