[2025-03-15T18:54:26.991+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T18:54:27.021+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:54:22.828974+00:00 [queued]>
[2025-03-15T18:54:27.035+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:54:22.828974+00:00 [queued]>
[2025-03-15T18:54:27.037+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T18:54:27.056+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): first_task> on 2025-03-15 18:54:22.828974+00:00
[2025-03-15T18:54:27.062+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T18:54:27.063+0000] {standard_task_runner.py:72} INFO - Started process 91 to run task
[2025-03-15T18:54:27.064+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'first_task', 'manual__2025-03-15T18:54:22.828974+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmp22659s2s']
[2025-03-15T18:54:27.065+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask first_task
[2025-03-15T18:54:27.153+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:54:22.828974+00:00 [running]> on host 52fb98bb51ef
[2025-03-15T18:54:27.282+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T18:54:22.828974+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T18:54:22.828974+00:00'
[2025-03-15T18:54:27.283+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T18:54:27.329+0000] {base.py:84} INFO - Retrieving connection 'spark_mm'
[2025-03-15T18:54:27.332+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark jobs/Script1.py
[2025-03-15T18:54:35.251+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 INFO SparkContext: Running Spark version 3.5.5
[2025-03-15T18:54:35.253+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-15T18:54:35.254+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 INFO SparkContext: Java version 17.0.14
[2025-03-15T18:54:35.394+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-15T18:54:35.697+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 INFO ResourceUtils: ==============================================================
[2025-03-15T18:54:35.698+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-15T18:54:35.699+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 INFO ResourceUtils: ==============================================================
[2025-03-15T18:54:35.699+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:35 INFO SparkContext: Submitted application: PythonWordCount
[2025-03-15T18:54:36.156+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-15T18:54:36.304+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO ResourceProfile: Limiting resource is cpu
[2025-03-15T18:54:36.305+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-15T18:54:36.615+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO SecurityManager: Changing view acls to: ***
[2025-03-15T18:54:36.616+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO SecurityManager: Changing modify acls to: ***
[2025-03-15T18:54:36.616+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO SecurityManager: Changing view acls groups to:
[2025-03-15T18:54:36.617+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO SecurityManager: Changing modify acls groups to:
[2025-03-15T18:54:36.618+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:36 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-15T18:54:37.126+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO Utils: Successfully started service 'sparkDriver' on port 34625.
[2025-03-15T18:54:37.218+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO SparkEnv: Registering MapOutputTracker
[2025-03-15T18:54:37.318+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-15T18:54:37.394+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-15T18:54:37.395+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-15T18:54:37.402+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-15T18:54:37.503+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-6aba30cb-741f-4b82-9bf6-b78aab14e1ea
[2025-03-15T18:54:37.521+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-03-15T18:54:37.544+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-15T18:54:37.798+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-15T18:54:37.918+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:37 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-15T18:54:38.203+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:38 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-03-15T18:54:38.291+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:38 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 32 ms (0 ms spent in bootstraps)
[2025-03-15T18:54:39.103+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250315185438-0000
[2025-03-15T18:54:39.116+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34923.
[2025-03-15T18:54:39.117+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO NettyBlockTransferService: Server created on 52fb98bb51ef:34923
[2025-03-15T18:54:39.120+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-15T18:54:39.132+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 52fb98bb51ef, 34923, None)
[2025-03-15T18:54:39.138+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO BlockManagerMasterEndpoint: Registering block manager 52fb98bb51ef:34923 with 413.9 MiB RAM, BlockManagerId(driver, 52fb98bb51ef, 34923, None)
[2025-03-15T18:54:39.142+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 52fb98bb51ef, 34923, None)
[2025-03-15T18:54:39.144+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 52fb98bb51ef, 34923, None)
[2025-03-15T18:54:39.193+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250315185438-0000/0 on worker-20250315185114-172.18.0.6-33537 (172.18.0.6:33537) with 2 core(s)
[2025-03-15T18:54:39.196+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO StandaloneSchedulerBackend: Granted executor ID app-20250315185438-0000/0 on hostPort 172.18.0.6:33537 with 2 core(s), 1024.0 MiB RAM
[2025-03-15T18:54:39.910+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:39 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-15T18:54:41.009+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:41 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250315185438-0000/0 is now RUNNING
[2025-03-15T18:54:42.500+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:42 INFO SparkContext: Starting job: collect at /opt/***/jobs/Script1.py:21
[2025-03-15T18:54:42.696+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:42 INFO DAGScheduler: Registering RDD 2 (reduceByKey at /opt/***/jobs/Script1.py:19) as input to shuffle 0
[2025-03-15T18:54:42.707+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:42 INFO DAGScheduler: Got job 0 (collect at /opt/***/jobs/Script1.py:21) with 2 output partitions
[2025-03-15T18:54:42.708+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:42 INFO DAGScheduler: Final stage: ResultStage 1 (collect at /opt/***/jobs/Script1.py:21)
[2025-03-15T18:54:42.709+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:42 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 0)
[2025-03-15T18:54:42.711+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:42 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 0)
[2025-03-15T18:54:42.717+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:42 INFO DAGScheduler: Submitting ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/jobs/Script1.py:19), which has no missing parents
[2025-03-15T18:54:43.324+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:43 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 10.9 KiB, free 413.9 MiB)
[2025-03-15T18:54:43.725+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:43 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 7.0 KiB, free 413.9 MiB)
[2025-03-15T18:54:43.805+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:43 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 52fb98bb51ef:34923 (size: 7.0 KiB, free: 413.9 MiB)
[2025-03-15T18:54:43.818+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:43 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2025-03-15T18:54:44.004+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:44 INFO DAGScheduler: Submitting 2 missing tasks from ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/jobs/Script1.py:19) (first 15 tasks are for partitions Vector(0, 1))
[2025-03-15T18:54:44.007+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:44 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[2025-03-15T18:54:47.948+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:47 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.6:34002) with ID 0,  ResourceProfileId 0
[2025-03-15T18:54:48.494+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:48 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.6:36171 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.6, 36171, None)
[2025-03-15T18:54:48.798+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:48 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.6, executor 0, partition 0, PROCESS_LOCAL, 9212 bytes)
[2025-03-15T18:54:48.810+0000] {spark_submit.py:488} INFO - 25/03/15 18:54:48 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1) (172.18.0.6, executor 0, partition 1, PROCESS_LOCAL, 9219 bytes)
[2025-03-15T18:55:01.644+0000] {spark_submit.py:488} INFO - 25/03/15 18:55:01 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@4049da5)) by listener AppStatusListener took 5.894199622s.
[2025-03-15T18:55:15.377+0000] {spark_submit.py:488} INFO - 25/03/15 18:55:15 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@190d42f2)) by listener AppStatusListener took 3.035038787s.
[2025-03-15T18:55:42.723+0000] {spark_submit.py:488} INFO - 25/03/15 18:55:42 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@39441dc3)) by listener AppStatusListener took 3.213204838s.
[2025-03-15T18:55:29.686+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-15T18:55:43.093+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:55:43.097+0000] {spark_submit.py:488} INFO - 25/03/15 18:55:43 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.6:36171 (size: 7.0 KiB, free: 434.4 MiB)
[2025-03-15T18:55:59.607+0000] {job.py:229} INFO - Heartbeat recovered after 71.68 seconds
[2025-03-15T18:56:10.355+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-15T18:56:30.651+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 101948 ms on 172.18.0.6 (executor 0) (1/2)
[2025-03-15T18:56:30.660+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 101846 ms on 172.18.0.6 (executor 0) (2/2)
[2025-03-15T18:56:30.662+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-03-15T18:56:30.673+0000] {job.py:229} INFO - Heartbeat recovered after 31.09 seconds
[2025-03-15T18:56:30.756+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO PythonAccumulatorV2: Connected to AccumulatorServer at host: 127.0.0.1 port: 41447
[2025-03-15T18:56:30.846+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO DAGScheduler: ShuffleMapStage 0 (reduceByKey at /opt/***/jobs/Script1.py:19) finished in 108.022 s
[2025-03-15T18:56:30.849+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO DAGScheduler: looking for newly runnable stages
[2025-03-15T18:56:30.851+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO DAGScheduler: running: Set()
[2025-03-15T18:56:30.852+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO DAGScheduler: waiting: Set(ResultStage 1)
[2025-03-15T18:56:30.853+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO DAGScheduler: failed: Set()
[2025-03-15T18:56:30.858+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO DAGScheduler: Submitting ResultStage 1 (PythonRDD[5] at collect at /opt/***/jobs/Script1.py:21), which has no missing parents
[2025-03-15T18:56:30.955+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 10.0 KiB, free 413.9 MiB)
[2025-03-15T18:56:31.036+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:30 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 6.0 KiB, free 413.9 MiB)
[2025-03-15T18:56:31.039+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 52fb98bb51ef:34923 (size: 6.0 KiB, free: 413.9 MiB)
[2025-03-15T18:56:31.042+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-03-15T18:56:31.046+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 1 (PythonRDD[5] at collect at /opt/***/jobs/Script1.py:21) (first 15 tasks are for partitions Vector(0, 1))
[2025-03-15T18:56:31.051+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO TaskSchedulerImpl: Adding task set 1.0 with 2 tasks resource profile 0
[2025-03-15T18:56:31.146+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 2) (172.18.0.6, executor 0, partition 0, NODE_LOCAL, 8821 bytes)
[2025-03-15T18:56:31.150+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 3) (172.18.0.6, executor 0, partition 1, NODE_LOCAL, 8821 bytes)
[2025-03-15T18:56:31.258+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 172.18.0.6:36171 (size: 6.0 KiB, free: 434.4 MiB)
[2025-03-15T18:56:31.495+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:31 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 172.18.0.6:34002
[2025-03-15T18:56:32.237+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 2) in 1036 ms on 172.18.0.6 (executor 0) (1/2)
[2025-03-15T18:56:32.248+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO TaskSetManager: Finished task 1.0 in stage 1.0 (TID 3) in 1090 ms on 172.18.0.6 (executor 0) (2/2)
[2025-03-15T18:56:32.249+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool
[2025-03-15T18:56:32.250+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO DAGScheduler: ResultStage 1 (collect at /opt/***/jobs/Script1.py:21) finished in 1.292 s
[2025-03-15T18:56:32.251+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO DAGScheduler: Job 0 is finished. Cancelling potential speculative or zombie tasks for this job
[2025-03-15T18:56:32.252+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO TaskSchedulerImpl: Killing all running tasks in stage 1: Stage finished
[2025-03-15T18:56:32.257+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO DAGScheduler: Job 0 finished: collect at /opt/***/jobs/Script1.py:21, took 109.808385 s
[2025-03-15T18:56:32.377+0000] {spark_submit.py:488} INFO - User1 2
[2025-03-15T18:56:32.378+0000] {spark_submit.py:488} INFO - Login 4
[2025-03-15T18:56:32.436+0000] {spark_submit.py:488} INFO - User2 3
[2025-03-15T18:56:32.442+0000] {spark_submit.py:488} INFO - failed 2
[2025-03-15T18:56:32.443+0000] {spark_submit.py:488} INFO - Viewed 1
[2025-03-15T18:56:32.444+0000] {spark_submit.py:488} INFO - profile 1
[2025-03-15T18:56:32.445+0000] {spark_submit.py:488} INFO - 10:03:00 1
[2025-03-15T18:56:32.447+0000] {spark_submit.py:488} INFO - User3 1
[2025-03-15T18:56:32.448+0000] {spark_submit.py:488} INFO - WARNING 1
[2025-03-15T18:56:32.451+0000] {spark_submit.py:488} INFO - 10:04:00 1
[2025-03-15T18:56:32.453+0000] {spark_submit.py:488} INFO - login 1
[2025-03-15T18:56:32.454+0000] {spark_submit.py:488} INFO - 10:06:00 1
[2025-03-15T18:56:32.455+0000] {spark_submit.py:488} INFO - User4 1
[2025-03-15T18:56:32.456+0000] {spark_submit.py:488} INFO - INFO 4
[2025-03-15T18:56:32.457+0000] {spark_submit.py:488} INFO - 2024-06-01 7
[2025-03-15T18:56:32.458+0000] {spark_submit.py:488} INFO - 10:00:00 1
[2025-03-15T18:56:32.460+0000] {spark_submit.py:488} INFO - successful 3
[2025-03-15T18:56:32.461+0000] {spark_submit.py:488} INFO - ERROR 2
[2025-03-15T18:56:32.462+0000] {spark_submit.py:488} INFO - 10:01:00 1
[2025-03-15T18:56:32.464+0000] {spark_submit.py:488} INFO - 10:02:00 1
[2025-03-15T18:56:32.466+0000] {spark_submit.py:488} INFO - Multiple 1
[2025-03-15T18:56:32.536+0000] {spark_submit.py:488} INFO - attempts 1
[2025-03-15T18:56:32.537+0000] {spark_submit.py:488} INFO - 10:05:00 1
[2025-03-15T18:56:32.540+0000] {spark_submit.py:488} INFO - Account 1
[2025-03-15T18:56:32.541+0000] {spark_submit.py:488} INFO - locked 1
[2025-03-15T18:56:32.542+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-15T18:56:32.544+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO SparkUI: Stopped Spark web UI at http://52fb98bb51ef:4040
[2025-03-15T18:56:32.547+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-15T18:56:32.549+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-15T18:56:32.670+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-15T18:56:32.947+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO MemoryStore: MemoryStore cleared
[2025-03-15T18:56:32.948+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO BlockManager: BlockManager stopped
[2025-03-15T18:56:32.987+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:32 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-15T18:56:33.038+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:33 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-15T18:56:33.075+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:33 INFO SparkContext: Successfully stopped SparkContext
[2025-03-15T18:56:33.476+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:33 INFO ShutdownHookManager: Shutdown hook called
[2025-03-15T18:56:33.477+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-8067380c-8d17-49af-9764-eb302bd5a24b
[2025-03-15T18:56:33.484+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-d7fb2102-db77-461c-b785-7a4f795d5d04
[2025-03-15T18:56:33.492+0000] {spark_submit.py:488} INFO - 25/03/15 18:56:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-d7fb2102-db77-461c-b785-7a4f795d5d04/pyspark-494625fe-0f05-4f42-8cb3-3eb9ffcc5fa7
[2025-03-15T18:56:33.623+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T18:56:33.624+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=solar_energy_crops_pipeline, task_id=first_task, run_id=manual__2025-03-15T18:54:22.828974+00:00, execution_date=20250315T185422, start_date=20250315T185427, end_date=20250315T185633
[2025-03-15T18:56:33.721+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-15T18:56:33.758+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T18:56:33.763+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
